version: 2

models:
  - name: stg_jaffle_shop__customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: stg_jaffle_shop__orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_jaffle_shop__customers')
              field: customer_id

